// <auto-generated />
using System;
using EventRegistration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventRegistration.Migrations
{
    [DbContext(typeof(EventRegistrationContext))]
    [Migration("20260117085918_SeedEventsAndTickets")]
    partial class SeedEventsAndTickets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventRegistration.Data.EventRegistrationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3274395e-ed85-4775-a732-6e2166b6844d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0fbfdf6f-e9be-47f7-a480-2ab0eb947039",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEL8mFAExCcPkdW35zU48vf18ZerkESZC5pK0nPDA+FeRJYUVFwe944UoQI/l4Xzj3w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "608b1949-6e85-4800-a9b5-ddc9f8cbfa5e",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        });
                });

            modelBuilder.Entity("EventRegistration.Domain.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Event");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Educational",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8259),
                            DateUpdated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8273),
                            Description = "Join us for Temasek Polytechnic's Open House! Explore our facilities, meet our faculty, and discover exciting courses.",
                            EventDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = true,
                            Location = "Temasek Polytechnic, Convention Centre",
                            Status = "Pending",
                            Title = "TP Open House",
                            TotalCapacity = 500,
                            Type = "Physical",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Professional",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8279),
                            DateUpdated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8280),
                            Description = "Join industry leaders and tech innovators for an inspiring day of talks covering AI, cloud computing, cybersecurity, and the future of technology in Southeast Asia.",
                            EventDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = true,
                            Location = "Marina Bay Sands Convention Centre",
                            Status = "Pending",
                            Title = "Tech Talks 2026",
                            TotalCapacity = 300,
                            Type = "Physical",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Entertainment",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8283),
                            DateUpdated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8284),
                            Description = "Experience the best of independent cinema from local and international filmmakers. Three days of screenings, Q&A sessions, and networking opportunities.",
                            EventDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = false,
                            Location = "National Museum of Singapore",
                            Status = "Pending",
                            Title = "Indie Film Festival",
                            TotalCapacity = 200,
                            Type = "Physical",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Sports",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8287),
                            DateUpdated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8288),
                            Description = "Challenge yourself in Singapore's premier marathon event! Choose from full marathon (42km), half marathon (21km), or 10km fun run. All fitness levels welcome.",
                            EventDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = true,
                            Location = "Marina Bay Area",
                            Status = "Pending",
                            Title = "City Marathon 2026",
                            TotalCapacity = 1000,
                            Type = "Physical",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Music",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8291),
                            DateUpdated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8291),
                            Description = "Singapore's biggest beach music festival featuring international and local artists across multiple stages. Two days of sun, sand, and amazing music!",
                            EventDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = true,
                            Location = "Siloso Beach, Sentosa",
                            Status = "Pending",
                            Title = "Summer Music Festival 2026",
                            TotalCapacity = 5000,
                            Type = "Physical",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Arts",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8294),
                            DateUpdated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8295),
                            Description = "Exhibitions, theater, and cultural events celebrating modern and contemporary art from Southeast Asian artists. Free admission for all visitors.",
                            EventDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = false,
                            Location = "City Gallery",
                            Status = "Pending",
                            Title = "Modern Art Exhibition",
                            TotalCapacity = 200,
                            Type = "Physical",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("EventRegistration.Domain.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Payment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 0.00m,
                            CreatedBy = "System",
                            Currency = "SGD",
                            DateCreated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8595),
                            DateUpdated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8596),
                            PaymentDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Free",
                            RegistrationId = 1,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("EventRegistration.Domain.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TicketId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TicketId");

                    b.ToTable("Registration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8739),
                            DateUpdated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8739),
                            Email = "",
                            EventId = 1,
                            FullName = "",
                            Quantity = 1,
                            RegistrationDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TicketId = 1,
                            TotalAmount = 0m,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("EventRegistration.Domain.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Ticket");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8883),
                            DateUpdated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8884),
                            EventId = 1,
                            Price = 0.00m,
                            Type = "Free Admission",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8887),
                            DateUpdated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8887),
                            EventId = 2,
                            Price = 75.00m,
                            Type = "General Admission",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8889),
                            DateUpdated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8890),
                            EventId = 2,
                            Price = 120.00m,
                            Type = "VIP Pass",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8892),
                            DateUpdated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8893),
                            EventId = 3,
                            Price = 35.00m,
                            Type = "Standard Pass",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8895),
                            DateUpdated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8895),
                            EventId = 3,
                            Price = 25.00m,
                            Type = "Student Pass",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8897),
                            DateUpdated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8898),
                            EventId = 4,
                            Price = 50.00m,
                            Type = "Runner Registration",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8900),
                            DateUpdated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8901),
                            EventId = 5,
                            Price = 45.00m,
                            Type = "General Admission",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8903),
                            DateUpdated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8904),
                            EventId = 5,
                            Price = 80.00m,
                            Type = "VIP Experience",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8906),
                            DateUpdated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8906),
                            EventId = 5,
                            Price = 30.00m,
                            Type = "Early Bird",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8908),
                            DateUpdated = new DateTime(2026, 1, 17, 16, 59, 16, 878, DateTimeKind.Local).AddTicks(8909),
                            EventId = 6,
                            Price = 0.00m,
                            Type = "Free Admission",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3274395e-ed85-4775-a732-6e2166b6844d",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EventRegistration.Domain.Registration", b =>
                {
                    b.HasOne("EventRegistration.Domain.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventRegistration.Domain.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Event");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("EventRegistration.Domain.Ticket", b =>
                {
                    b.HasOne("EventRegistration.Domain.Event", null)
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EventRegistration.Data.EventRegistrationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EventRegistration.Data.EventRegistrationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventRegistration.Data.EventRegistrationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EventRegistration.Data.EventRegistrationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventRegistration.Domain.Event", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
